### ISSUE TITLE
No Apple Silicon binary available through Homebrew

### ISSUE THREAD

**Issue by mstrzele** [humio/cli#103]
Is it possible to release a new version to trigger GoReleaser to build an Apple Silicon binary and update Humio's Homebrew tap?

**Comment by SaaldjorMike** [comment]
We've recently cut a new release which now publishes the additional binaries which also gets included in the homebrew formula: https://github.com/humio/homebrew-humio/commit/5aa9e8c6f0a95419198fa1f677174316cf3c6685
