### ISSUE TITLE
Problem configuring humioctl on Windows

### ISSUE THREAD

**Issue by exquisitus** [humio/cli#108]
Hello,

I am a new user.

While trying to configure humioctl on Windows (cmd), I get asked for the humio instance, and I give my answer. The testing of the connection then seems successful. I reject the offer to open a browser and then, bam, I immediately get an error that something is invalid with my API Token, before ever getting a chance to input my token.

Notice that in my screenshot, somethings are different compared to https://library.humio.com/humio-server/humioctl.html :
- "Testing Connection ..." (3 times) comes on the same line and not on different lines.
- More newlines and empty lines seem to be missing

```
C:\>humioctl -v
humioctl 0.29.1 (81db24728f67d724249dc6c72a2fc17f4abf938c on 2022-03-28T13:24:04Z)
```
![humioctl_bug](https://user-images.githubusercontent.com/8738944/181262017-31b1ef33-f94e-4dc6-bed3-b752dc5d503a.jpg)

**Comment by tankbusta** [comment]
Hey @exquisitus 

This should be fixed now. Until a new version is tagged, you can get the fix by installing the latest version from the master branch 

'$ go install github.com/humio/cli/cmd/humioctl@master'
