### ISSUE TITLE
humioctl requires more permissions than the cloud webui for the same operations

### ISSUE THREAD

**Issue by wknapik** [humio/cli#26]
Hi,

I'd like to use humioctl to add views and add users to views. Apparently the latter requires root access, which, as a user of Humio Cloud (v1.11.0), I don't have.

This makes no apparent sense, since I can already add users to views with the same non-root user, using the webui (which, presumably, uses the same API as humioctl).

Please allow Humio Cloud users to use the full functionality of humioctl.

**Comment by danielamkaer** [comment]
Currently there is no support in the CLI for adding views or adding users to views. Which commands are you referring to?

**Comment by wknapik** [comment]
Hi @danielamkaer,

I never used humioctl before, I just ran it to see what's supported, saw CRUD operations on `users` available and thought I'd try adding a user to a pre-existing view, but then noticed the `[Root Only]` note and realized I won't be able to use that with Humio Cloud.

Even if view creation is not available, being able to use humioctl just to manage users would be very useful.

I don't know if those are users in the same sense as in the API I'm already using, but given no indication to the contrary, I assumed that's the case.

Is there any timeline for the development of humioctl ? I'd be interested in tracking what's next in line to be implemented and when it actually becomes available.

Thanks.

**Comment by andejens** [comment]
We have recently updated our cloud to bring it on par with self-hosted with respect to user management and RBAC. We are looking into how we can utilise this in our CLI project. No concrete timeframes yet. As suggested elsewhere - let's set up a meeting so we get a better idea about how we can support your use-case.

**Comment by danielamkaer** [comment]
Closing this. We now have commands for showing/manipulating views and users which only requires organization root permission.
