### ISSUE TITLE
Additional installation instructions needed

### ISSUE THREAD

**Issue by wknapik** [humio/cli#27]
Hi,

It seems the most universal installation method is not mentioned in the README. `go get github.com/humio/cli` is very simple, cross-platform and widely known among go developers. I'd suggest including it in the docs.

There's currently one wrinkle with that approach - the name of the binary is not `humioctl` - it's `cli`, which is derived from the last segment of the url. The end user could just do `mv "$GOPATH/bin/"{cli,humioctl}` after running `go get`, but that's not great, so if that could be sorted out, that would be nice.

Also, even if we forget about `go get`, the current installation instructions seem to conflate "Linux" and "Ubuntu", which are not the same thing. At least a curl-a-release-tarball-from-github-and-unpack approach could be described for users who can't use a package manager like `snap`.

**Comment by lucperkins** [comment]
Agreed that this would be useful, given #30. Adding a `humioctl` directory under `cmd` would accomplish this.
