### ISSUE TITLE
Command Wishlist

### ISSUE THREAD

**Issue by anagrius** [humio/cli#3]
This issue is a meta issue for collecting inspiration for what you would like to see in a CLI for Humio. please comment to suggest commands or discuss functionality.

You can also join http://community.humio.com/ Slack community to discuss it there as well.

# SUGGESTED COMMANDS

# Dataspaces

- `dataspaces create --retention 2TB "my-dataspace"`
- `dataspaces delete "my-dataspace"`
- `dataspaces set-retention "my-dataspace" --size 3TB --max-age 6months`

# Users

- `add-user --role=admin foo@example.com my-dataspace`
- `set-role foo@example.com`
- `remove-user foo@example.com my-dataspace`

# Searching

- `stream --format=json "my | filter | query"`
- `run --from=24h "my aggrgate query | groupby(foo)"`

# Queries 

- `queries list my-ds`
- `queries my-ds/my-query "foo | bar | $baz()"`
- `queries remove my-ds/my-query`
- `queries show my-ds/my-query`

# Alerts

- `alerts list my-ds`
- `alerts history my-alert`
- `alerts disable my-alert`
- `alerts enable my-alert`
- `alerts create --from 24h my-ds/my-alert "/error/i | count() | _count > 0"`
- `alerts delete my-ds/my-alert`

# Dashboards

- `dashboards create my-ds my-dash`
- `dashboards delete my-ds my-dash`
- `dashboards list my-ds`
- `dashboards clone community-dashboards/nginx-performance`
- `dashboards share --name my-shared-link my-ds my-dash`

# Ingest Logs

Example:

`example app | humio ingest -ds my-ds`
`make build | humio`

**Comment by krestenkrab** [comment]
`login` command - write API token to `~/.humio` like this: opens a websocket to the server to get a unique session id *and* launches a browser using that token. When the user logs in using the browser, the cli receives the API token via the websocket and writer it to a config file.
