### ISSUE TITLE
humioctl parser export no longer works on 0.27

### ISSUE THREAD

**Issue by andrem123456** [humio/cli#38]
In version 0.26 I was able to run a command that looks like this

`humioctl parsers export -o ./ humio kv`

and it would extract the parser yaml template fine.
Since upgrading to 0.27 I can no longer run this command and returns this response.

```
andre$ humioctl parsers export -o ./ humio kv
Error fetching parsers: non-200 OK status code: 400 Bad Request body: "{\"data\":null,\"errors\":[{\"message\":\"Cannot query field 'yamlTemplate' on type 'Parser'. (line 1, column 111):\\nquery($parserName:String!$repositoryName:String!){repository(name: $repositoryName){parser(name: $parserName){yamlTemplate}}}\\n                                                                                                              ^\",\"locations\":[{\"column\":111,\"line\":1}]}]}"
```

**Comment by anagrius** [comment]
Hi Andre, It was removed. It was remove in preparation to the upcoming packages feature where the format of parsers and other assets has changes. tbh we did not expect that anyone was using this old command, I will re-add it, until the release of packages at which point it will be removed.

Sorry for the inconvenience, I will try to get a new version out soon

**Comment by camilleacey** [comment]
@anagrius why did you close this?

**Comment by anagrius** [comment]
Because of my conversation with Andre. We are not changing this back. The cli can be used in a previous version 26 if the previous behavior is required.

**Comment by camilleacey** [comment]
Thanks, @anagrius . I've updated our system accordingly.
