### ISSUE TITLE
Load token from a file

### ISSUE THREAD

**Issue by mwl** [humio/cli#5]
Quite often you want to be able to point to where the token can be found, i.e.

```
export HUMIO_API_TOKEN_FILE=/data/humio-data/local-admin-token.txt
export HUMIO_URL=http://localhost:8080/
humio -r humio token list
```

This way, we can distribute this cli with the Docker images and a config file so you can

```
docker exec humio humio -r humio token list
docker exec humio humio users add-root "king-julian@madagascar.gov"
# etc
```

from the host machine

**Comment by anagrius** [comment]
We also have support for a `.humio` config file in the home directory.

**Comment by mwl** [comment]
True, but the challenge here is that the `local-admin-token.txt` changes all the time so putting it into another file doesn't solve it.

**Comment by anagrius** [comment]
Ok. I will add it

**Comment by mwl** [comment]
Thanks love 😘

**Comment by anagrius** [comment]
Or you could simply make a wrapper for humio-cli that would export that file:

```
#!/bin/user/env bash

export HUMIO_API_TOKEN=`cat /data/humio-data/local-admin-token.txt`
/path/to/real/humio "$@"
```

**Comment by anagrius** [comment]
It is not that I don't want to add it, it is just that I want to make sure it is generally useful. If you think that script is more trouble then, I think it is fine to add.

**Comment by mwl** [comment]
True, but wrappers are an anti-pattern IMO and writing wrappers for our own stack should be below our standards

**Comment by anagrius** [comment]
Fixed
