### ISSUE TITLE
Different output formats

### ISSUE THREAD

**Issue by estahn** [humio/cli#50]
I'm trying to export all alerts with `humioctl alerts export`, which requires the name of the alert. Therefore I'm trying to get a list of alerts with `humioctl alerts list`, but I only get a tabular format back which can't be captured via stdout/stderr.

Example:
```
 humioctl alerts list myview 2>&1 > foobar
```

The file is empty but the terminal shows a list of events.

**Comment by danielamkaer** [comment]
The order of redirection is important, try

`humioctl alerts list myview > foobar 2>&1`

**Comment by estahn** [comment]
> The order of redirection is important

@danielamkaer Thanks for pointing this out. This works as expected. 👍 

The issue of different output format still remains.

**Comment by SaaldjorMike** [comment]
Given that we've merged in https://github.com/humio/cli/pull/90 I'm going to close this issue. This will be part of the next `humioctl` release. You can also try it out now if you compile the project yourself until the release gets published:
```
git clone https://github.com/humio/cli.git humio-cli
cd humio-cli
make
bin/humioctl alerts list myview
```

It is now also possible to output the list in using JSON formatting:
```
bin/humioctl alerts list myview --format json
```
