### ISSUE TITLE
Passing more then one key value pair into --connection flag

### ISSUE THREAD

**Issue by stachdude** [humio/cli#79]
Hi all,

solution eludes me. I'm trying to pass more then one key value pair for Views config (update, create).

`humioctl views update Test --connection`

However no matter what, I always end with just one being passed. Please anybody enlighten me ! :)

**Comment by SaaldjorMike** [comment]
The connections flag is a comma-separated list of key, value pairs. Each pair represents the repository name and the filter for the connection. I've submitted a PR to include an example into the `humioctl` help output.

Perhaps you could give this diff a quick read to see how it works: https://github.com/humio/cli/pull/97/files
